### ISSUE TITLE
jaeger-ingester crash

### ISSUE THREAD

**Issue by panjunDev** [jaegertracing/jaeger#1522]
hello
I used jaeger-ingester to subscribe message from kafka and write to elasticsearch,but a couple of minutes later,the ingester crash,here are error msgs:

```
{"level":"warn","ts":1557201582.111119,"caller":"consumer/deadlock_detector.go:122","msg":"Signalling partition close due to inactivity","partition":0}
{"level":"info","ts":1557201582.111341,"caller":"consumer/consumer.go:148","msg":"Closing partition due to inactivity","partition":0}
{"level":"debug","ts":1557201582.1113782,"caller":"processor/parallel_processor.go:75","msg":"Initiated shutdown of processor goroutines"}
{"level":"info","ts":1557201582.1136134,"caller":"processor/parallel_processor.go:78","msg":"Completed shutdown of processor goroutines"}
{"level":"debug","ts":1557201582.1137452,"caller":"consumer/deadlock_detector.go:195","msg":"Closing deadlock detector","partition":0}
{"level":"info","ts":1557201582.1138122,"caller":"consumer/consumer.go:155","msg":"Closing partition consumer","partition":0}
{"level":"info","ts":1557201582.1138837,"caller":"consumer/deadlock_detector.go:115","msg":"Closing ticker routine","partition":0}
{"level":"info","ts":1557201582.2355347,"caller":"consumer/consumer.go:158","msg":"Closed partition consumer","partition":0}
{"level":"info","ts":1557201582.235707,"caller":"consumer/consumer.go:173","msg":"Finished handling errors","partition":0}
panic: counter cannot decrease in value

goroutine 67 [running]:
github.com/jaegertracing/jaeger/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc0002ec5c0, 0xbff0000000000000)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/prometheus/client_golang/prometheus/counter.go:71 +0xa3
github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-lib/metrics/prometheus.(*counter).Inc(0xc000334ea0, 0xffffffffffffffff)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/uber/jaeger-lib/metrics/prometheus/factory.go:223 +0x46
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).handleMessages(0xc000144f70, 0xf221a0, 0xc0001a8360)

	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:149 +0x9e8
created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:91 +0x172
```

**Comment by pavolloffay** [comment]
Please add what version of jaeger are you using.

**Comment by yurishkuro** [comment]
I think it's fixed by #1485

**Comment by pavolloffay** [comment]
@panjunDev 1.12.0 with the fix has been released. Could you please test it out?

**Comment by panjunDev** [comment]
> @panjunDev 1.12.0 with the fix has been released. Could you please test it out?

thank you,1.12.0  has finished testing,it works fine.

**Comment by panjunDev** [comment]
> @panjunDev 1.12.0 with the fix has been released. Could you please test it out?
hi,friend,the ingester still crash,when it run for a long time,here is error msgs:
created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:93 +0x1d9\n\ngoroutine 9900 [select, 2 minutes]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*partitionConsumer).WaitFor(0xc0020d23f0, 0xc0012f3c80, 0xc000315620)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/partitions.go:88 +0x14d\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*Consumer).createConsumer.func1(0xc0012f3c80)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/consumer.go:832 +0x50\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc001892780, 0xc00136ef40)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/util.go:73 +0x89\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*loopTomb).Go\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/util.go:69 +0x66\n\ngoroutine 9899 [select, 2 minutes]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).monitorForPartition(0xc000310218, 0xc0015f8780, 0x1)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:113 +0xfd\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).startMonitoringForPartition\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:102 +0x1ae\n\ngoroutine 9781 [select]:\nnet/http.(*persistConn).writeLoop(0xc00019b320)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1958 +0x113\ncreated by net/http.(*Transport).dialConn\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1358 +0xb0d\n\ngoroutine 9780 [IO wait]:\ninternal/poll.runtime_pollWait(0x7fd867c13128, 0x72, 0xffffffffffffffff)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/netpoll.go:182 +0x56\ninternal/poll.(*pollDesc).wait(0xc001344798, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x9b\ninternal/poll.(*pollDesc).waitRead(...)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Read(0xc001344780, 0xc0002c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/internal/poll/fd_unix.go:169 +0x19b\nnet.(*netFD).Read(0xc001344780, 0xc0002c7000, 0x1000, 0x1000, 0xc001596600, 0xc000f17b00, 0xc0032ffdd0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/fd_unix.go:202 +0x4f\nnet.(*conn).Read(0xc0022b98e8, 0xc0002c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/net.go:177 +0x69\nnet/http.(*persistConn).Read(0xc00019b320, 0xc0002c7000, 0x1000, 0x1000, 0x459e70, 0xc0032ffe88, 0x2)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1524 +0x7b\nbufio.(*Reader).fill(0xc003320f60)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/bufio/bufio.go:100 +0x10f\nbufio.(*Reader).Peek(0xc003320f60, 0x1, 0x2, 0x0, 0x0, 0xc001596500, 0x0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/bufio/bufio.go:138 +0x4f\nnet/http.(*persistConn).readLoop(0xc00019b320)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1677 +0x1a3\ncreated by net/http.(*Transport).dialConn\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1357 +0xae8\n\ngoroutine 9922 [select]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).sendAndReceive(0xc000171680, 0x122a300, 0xc0009f5d20, 0x120a940, 0xc001da32c0, 0xc0019cc390, 0x1b1c710)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:715 +0x145\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).Fetch(0xc000171680, 0xc0009f5d20, 0xc000000000, 0xc00136d598, 0xc0017f2be8)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:358 +0x70\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*brokerConsumer).fetchNewMessages(0xc001847090, 0x0, 0x0, 0x0)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/consumer.go:882 +0x50a\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*brokerConsumer).subscriptionConsumer(0xc001847090)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/consumer.go:765 +0x121\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.withRecover(0xc002a94530)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/utils.go:45 +0x43\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*consumer).newBrokerConsumer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/consumer.go:706 +0x19c\n\ngoroutine 9524 [select, 2 minutes]:\nnet/http.(*persistConn).writeLoop(0xc000edf7a0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1958 +0x113\ncreated by net/http.(*Transport).dialConn\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1358 +0xb0d\n","stacktrace":"github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163"}
panic: No messages processed in the last check interval

goroutine 49 [running]:
github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000b4f20, 0xc0000f2180, 0x2, 0x2)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x546
github.com/jaegertracing/jaeger/vendor/go.uber.org/zap.(*Logger).Panic(0xc0000732c0, 0x10c3005, 0x30, 0xc0000f2180, 0x2, 0x2)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/logger.go:225 +0x7f
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1(0xc0ffffffff)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71 +0x413
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1(0xc000310218, 0xc0002885c0)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163 +0x135
created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:152 +0x18

**Comment by pavolloffay** [comment]
It seems to fail on different lines

> 	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71 +0x413

**Comment by panjunDev** [comment]
> It seems to fail on different lines
> 
> > /home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71 +0x413

**Comment by panjunDev** [comment]
> It seems to fail on different lines
> 
> > /home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71 +0x413

so,what i should do,please help me.

**Comment by panjunDev** [comment]
@pavolloffay @yurishkuro 

> > @panjunDev 1.12.0 with the fix has been released. Could you please test it out?
> 
> hi,friend,the ingester still crash,when it run for a long time,here is error msgs:
> 
> ```
> created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:93 +0x1d9\n\ngoroutine 9900 [select, 2 minutes]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*partitionConsumer).WaitFor(0xc0020d23f0, 0xc0012f3c80, 0xc000315620)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/partitions.go:88 +0x14d\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*Consumer).createConsumer.func1(0xc0012f3c80)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/consumer.go:832 +0x50\ngithub.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc001892780, 0xc00136ef40)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/util.go:73 +0x89\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster.(*loopTomb).Go\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/bsm/sarama-cluster/util.go:69 +0x66\n\ngoroutine 9899 [select, 2 minutes]:\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).monitorForPartition(0xc000310218, 0xc0015f8780, 0x1)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:113 +0xfd\ncreated by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).startMonitoringForPartition\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:102 +0x1ae\n\ngoroutine 9781 [select]:\nnet/http.(*persistConn).writeLoop(0xc00019b320)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1958 +0x113\ncreated by net/http.(*Transport).dialConn\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1358 +0xb0d\n\ngoroutine 9780 [IO wait]:\ninternal/poll.runtime_pollWait(0x7fd867c13128, 0x72, 0xffffffffffffffff)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/netpoll.go:182 +0x56\ninternal/poll.(*pollDesc).wait(0xc001344798, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x9b\ninternal/poll.(*pollDesc).waitRead(...)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Read(0xc001344780, 0xc0002c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/internal/poll/fd_unix.go:169 +0x19b\nnet.(*netFD).Read(0xc001344780, 0xc0002c7000, 0x1000, 0x1000, 0xc001596600, 0xc000f17b00, 0xc0032ffdd0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/fd_unix.go:202 +0x4f\nnet.(*conn).Read(0xc0022b98e8, 0xc0002c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/net.go:177 +0x69\nnet/http.(*persistConn).Read(0xc00019b320, 0xc0002c7000, 0x1000, 0x1000, 0x459e70, 0xc0032ffe88, 0x2)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1524 +0x7b\nbufio.(*Reader).fill(0xc003320f60)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/bufio/bufio.go:100 +0x10f\nbufio.(*Reader).Peek(0xc003320f60, 0x1, 0x2, 0x0, 0x0, 0xc001596500, 0x0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/bufio/bufio.go:138 +0x4f\nnet/http.(*persistConn).readLoop(0xc00019b320)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1677 +0x1a3\ncreated by net/http.(*Transport).dialConn\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1357 +0xae8\n\ngoroutine 9922 [select]:\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).sendAndReceive(0xc000171680, 0x122a300, 0xc0009f5d20, 0x120a940, 0xc001da32c0, 0xc0019cc390, 0x1b1c710)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:715 +0x145\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*Broker).Fetch(0xc000171680, 0xc0009f5d20, 0xc000000000, 0xc00136d598, 0xc0017f2be8)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/broker.go:358 +0x70\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*brokerConsumer).fetchNewMessages(0xc001847090, 0x0, 0x0, 0x0)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/consumer.go:882 +0x50a\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*brokerConsumer).subscriptionConsumer(0xc001847090)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/consumer.go:765 +0x121\ngithub.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.withRecover(0xc002a94530)\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/utils.go:45 +0x43\ncreated by github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama.(*consumer).newBrokerConsumer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/Shopify/sarama/consumer.go:706 +0x19c\n\ngoroutine 9524 [select, 2 minutes]:\nnet/http.(*persistConn).writeLoop(0xc000edf7a0)\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1958 +0x113\ncreated by net/http.(*Transport).dialConn\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/transport.go:1358 +0xb0d\n","stacktrace":"github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71\ngithub.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163"}
> panic: No messages processed in the last check interval
> 
> goroutine 49 [running]:
> github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000b4f20, 0xc0000f2180, 0x2, 0x2)
> 	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x546
> github.com/jaegertracing/jaeger/vendor/go.uber.org/zap.(*Logger).Panic(0xc0000732c0, 0x10c3005, 0x30, 0xc0000f2180, 0x2, 0x2)
> 	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/go.uber.org/zap/logger.go:225 +0x7f
> github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.newDeadlockDetector.func1(0xc0ffffffff)
> 	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:71 +0x413
> github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start.func1(0xc000310218, 0xc0002885c0)
> 	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:163 +0x135
> created by github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*deadlockDetector).start
> 	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/deadlock_detector.go:152 +0x18
> ```

**Comment by yurishkuro** [comment]
if you are not getting constant inflow of messages in Kafka, the deadlock detector will think something is wrong and kill the ingester. It's by design to work around certain bugs in the kafka driver. If you don't want this behavior you can set the deadlock interval to 0:
```shell
$ go run ./cmd/ingester  help | grep deadlock
      --ingester.deadlockInterval duration              Interval to check for deadlocks. 
                         If no messages gets processed in given time, ingester app will exit. 
                         Value of 0 disables deadlock check. (default 1m0s)
```
