### ISSUE TITLE
Existing traces can't be searched from the trace id lookup UI

### ISSUE THREAD

**Issue by ndrscodes** [jaegertracing/jaeger#3227]
**Describe the bug**
Trace id's older than a few days cannot be searched through the trace lookup UI (the search bar at the top), when searching for an older trace, the API 404 page is shown.
There is a (relatively simple and very curious) fix for this: The trace lookup becomes available again as soon as traces for the service in question are serached within the expected time frame of the trace.
For example, i am unable to search for a trace ID that's about 10 days old, but once i search for traces around the same timeframe i expect the trace to be available in jaeger, once i've found it through the search, the trace lookup starts to work again for this trace.
Interestingly, it only works within the same browser tab. Copying the traces URL and pasting it into another tab yields an API 404 error.

**To Reproduce**
1. search for a trace id that's a few days or weeks old using the trace lookup -> likely will produce a 404 error
2. search the service in question for traces within the same timeframe
3. use the trace lookup again -> likely will show the correct trace and it's spans
4. copy the URL of the trace, paste it into another browser tab -> likely, a 404 error will be produced once again

**Expected behavior**
the trace lookup should find traces regardless of the time they were produced at

**Screenshots**
before using search:
![image](https://user-images.githubusercontent.com/62462135/130574497-41b44ba7-5236-43e4-a58a-6f39474440f1.png)
after using search:
![image](https://user-images.githubusercontent.com/62462135/130575417-f7c8fed4-2889-4f4a-a3c4-97344d4aa77f.png)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.25.0 (also 1.23.0)
 - Deployment: bare metal

**What troubleshooting steps did you try?**
Verified the sampling strategy, verified the presence of the trace in question

**Additional context**
this issue resembles Issue #2816

**Comment by ndrscodes** [comment]
I had a look at the ES SpanReader source code and found out about the ES_MAX_SPAN_AGE env variable and i'm feeling pretty stupid now because i should have found out about it much earlier. I've still got some testing to do, but i am pretty sure it fixed the issues we were having.

**Comment by jpkrohling** [comment]
@ndrscodes, sorry that it took you that much to figure it out, and I blame it on us rather than on you. What do you think could have saved you time on this issue? Perhaps a mention about this elsewhere in the docs? A mention about it in the 404 page?

**Comment by ndrscodes** [comment]
@jpkrohling it might be a good idea to further test the behaviour of the ES_MAX_SPAN_AGE setting. The problem was that i was able to search the trace after it had been found through the manual search first, which to me indicates that there is some issue leading to this inconsistent behaviour. Traces should never be searchable if they are older than the specified ES_MAX_SPAN_AGE, even if it was found through the manual search before. 
A hint indicating the current ES_MAX_SPAN_AGE could also help on the 404 page.
Is there any reason behind setting the variable to a default value this low (72h0m0s) in the first place?

**Comment by jpkrohling** [comment]
Perhaps @albertteoh or @pavolloffay are able to give some more information about this.

**Comment by ndrscodes** [comment]
@jpkrohling we just noticed that when setting the value too high, the jaeger api returns the following error which originates from the underlying elasticstack: `HTTP Error: search services failed: elastic: Error 400 (Bad Request): An HTTP line is larger than 4096 bytes. [type=too_long_frame_exception]`
Any idea what might cause this?

**Comment by albertteoh** [comment]
@ndrscodes for posterity, was this issue resolved because you had [fixed something in your config](https://github.com/jaegertracing/jaeger/issues/2816#issuecomment-904459194)? Was it resolved by enabling ES Rollover or reducing the max span age as you had suggested in https://github.com/jaegertracing/jaeger-ui/issues/486#issuecomment-906155658?

Is there still something that could be done to reduce confusion/improve troubleshooting experience?

**Comment by ndrscodes** [comment]
@albertteoh i posted the original issue because of the inconsistent behavior. The trace search will find a trace if the timespan it was produced in was first searched using the manual search. This led me to believe there was some kind of bug. 
I can understand the decision that the trace search should work this way, but i think the trace search should never be able to find a trace if the trace was produced previous to the max-span-age timeframe in order to avoid confusion. Additionally, the current max-span-age could be announced somewhere on the 404 page. 

As for the other problem that i am facing now, maybe there should be a warning somewhere in the docs that indicates the maximum safe max-span-age if ES Rollover is not active. And additionally, i have yet to find a way to prepare jaeger for ES Rollover in a 'bare metal' system without docker, so that might need - some explanation as well (if it is possible somehow).

**Comment by nata7che** [comment]
Hi, I'm running the latest (1.26) query docker and encountering the same issue. changing the `--es.max-span-age` doesn't seem to help, and I'm still unable to view the trace visualization. I'm currently not running with a rollup but with manual daily indices. any ideas as to what else I could check/do?

**Comment by sanjaygopinath89** [comment]
@jpkrohling Faced same issue. It will be better to mention this along with the trace cleaning https://www.jaegertracing.io/docs/1.27/deployment/#remove-old-data  ( implementation that we do for specific retention). Those who are new to Jaeger may think that whatever trace available will be searchable. In my case once I implement retention I thought the trace within that will be searchable, didn't know that there is another configuration which control the search.    `--es.max-span-age=336h`
